apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    name: minio-ghost
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: hdd
  local:
    path: /home/minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hostname
