apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: kerberos/vault:1.0.856111762
        #imagePullPolicy: Always
        resources:
          limits:
            memory: 2048Mi
            cpu: 2000m
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: mongodb
        # Injecting the ca-certificates inside the container.
        #volumeMounts:
        #- name: rootcerts
        #  mountPath: /etc/ssl/certs/ca-certificates.crt
        #  subPath: ca-certificates.crt
        env:
        - name: GIN_MODE
          value: release
        - name: KERBEROS_LOGIN_USERNAME
          value: "root"
        - name: KERBEROS_LOGIN_PASSWORD
          value: "kerberos"
        # MQTT broker to be used for on-demand forwarding.
        - name : MQTTURI
          value: "tcp://mqtt.kerberos.io:1883"
        - name : MQTT_USERNAME
          value: ""
        - name : MQTT_PASSWORD
          value: ""
        # If you have a chained vault setup, enable this.
        - name: CONTINUOUS_FORWARDING
          value: "false"
      #volumes:
      #- name: rootcerts
      #  configMap:
      #    name: rootcerts
---
apiVersion: v1
kind: Service
metadata:
  name: vault-lb
  labels:
    app: vault
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: frontend
    protocol: TCP
  selector:
    app: vault