version: '3'

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  kerberos-vault:
    image: 'kerberos/vault:1.0.709240939'
    restart: always
    container_name: 'kerberos-vault'
    hostname: 'kerberos-vault'
    ports:
      - '80'
      - '8081'
    volumes:
      - "./vault:/vault"
    environment:
      - GIN_MODE=release
      - STORAGE_API_URL=kerberos-vault-api.domain.tld
      - KERBEROS_LOGIN_USERNAME=root
      - KERBEROS_LOGIN_PASSWORD=pass
      - MONGODB_HOST=kerberos-mongo
      - MONGODB_DATABASE_CREDENTIALS=admin
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=pass
      - MONGODB_DATABASE_STORAGE=KerberosStorage
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kerberos-vault.rule=Host(`kerberos-vault.domain.tld`)'
      - 'traefik.http.routers.kerberos-vault.entrypoints=web'
      - 'traefik.http.routers.kerberos-vault.tls=false'
      - 'traefik.http.routers.kerberos-vault.tls.certresolver=leresolver'
      - "traefik.http.routers.kerberos-vault.service=kerberos_vault"
      - 'traefik.http.services.kerberos_vault.loadbalancer.server.port=80'
      - 'traefik.http.routers.kerberos-vault-api.rule=Host(`kerberos-vault-api.domain.tld`)'
      - 'traefik.http.routers.kerberos-vault-api.entrypoints=web'
      - 'traefik.http.routers.kerberos-vault-api.tls=false'
      - 'traefik.http.routers.kerberos-vault-api.tls.certresolver=leresolver'
      - "traefik.http.routers.kerberos-vault-api.service=kerberos_vault_api"
      - 'traefik.http.services.kerberos_vault_api.loadbalancer.server.port=8081'

  kerberos-mongo:
    image: 'mongo:4.4.16'
    container_name: 'kerberos-mongo'
    hostname: 'kerberos-mongo'
    ports:
      - 27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass

  minio:
    image: 'quay.io/minio/minio'
    container_name: 'minio'
    hostname: 'minio'
    command: server /data --console-address ":9090"
    ports:
      - 9000
      - 9090
    volumes:
      - ./minio:/data
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
      - MINIO_DOMAIN=domain.tld
      - MINIO_DOMAINS=domain.tld
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.minio.rule=Host(`minio.domain.tld`)'
      - 'traefik.http.routers.minio.entrypoints=web'
      - 'traefik.http.routers.minio.tls=false'
      - 'traefik.http.routers.minio.tls.certresolver=leresolver'
      - "traefik.http.routers.minio.service=minio"
      - 'traefik.http.services.minio.loadbalancer.server.port=9000'
      - 'traefik.http.routers.minio-console.rule=Host(`minio-console.domain.tld`)'
      - 'traefik.http.routers.minio-console.entrypoints=web'
      - 'traefik.http.routers.minio-console.tls=false'
      - 'traefik.http.routers.minio-console.tls.certresolver=leresolver'
      - "traefik.http.routers.minio-console.service=minio-console"
      - 'traefik.http.services.minio-console.loadbalancer.server.port=9090'
    

volumes:
  kerberos-data:

networks:
  default:
      name: cluster-net
      external: true
