apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-handler
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kafka-handler
    spec:
      containers:
        - name: kafka-handler
          image: kerberos/kafka-handler:1.1
          imagePullPolicy: Always
          env:
            # Kerberos Vault
            - name: STORAGE_URI
              value: "https://vault.kerberos.xxx/api"
            - name: STORAGE_ACCESS_KEY
              value: "xxx"
            - name: STORAGE_SECRET
              value: "xxx"

            # Kafka
            - name: KAFKA_QUEUE_NAME
              value: "mytopic"
            - name: KAFKA_GROUP
              value: "group"
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: KAFKA_MECHANISM
              value: "PLAIN"
            - name: KAFKA_SECURITY
              value: "SASL_PLAINTEXT"
            - name: KAFKA_USERNAME
              value: "Yourusername"
            - name: KAFKA_PASSWORD
              value: "Yourpassword"
