apiVersion: apps/v1
kind: Deployment
metadata:
  name: kerberos-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kerberos-vault
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kerberos-vault
    spec:
      containers:
      - name: kerberos-vault
        image: kerberos/vault:1.0.397479393
        #imagePullPolicy: Always
        resources:
          limits:
            memory: 1536Mi
        ports:
          - containerPort: 80
          - containerPort: 8081
        env:
        - name: KERBEROS_LOGIN_USERNAME
          value: "root"
        - name: KERBEROS_LOGIN_PASSWORD
          value: "kerberos"
        - name: KERBEROS_CLOUD_ENABLED
          value: "true"
        # By default the API will be served on api.vaultdomain.com (api.) is prefixed.
        # If you prefer another hostname for the API e.g. myvaultapi-vaultdomain.com
        # Enable and change this variable to "myvaultapi-vaultdomain.com"
        #- name: STORAGE_API_URL
        #  value: "myvaultapi-storagedomain.com"
        - name: MONGODB_DATABASE_CLOUD
          value: "Kerberos"
        - name: MONGODB_DATABASE_FACTORY
          value: "KerberosFactory"
        - name: MONGODB_DATABASE_STORAGE
          value: "KerberosStorage"
        - name: MONGODB_HOST
          value: "mongodb.mongodb"
        - name: MONGODB_DATABASE_CREDENTIALS
          value: "admin"
        - name: MONGODB_USERNAME
          value: "root"
        - name: MONGODB_PASSWORD
          value: "xxxxxxxxxx"
        - name: LICENSE_API_URL
          value: "https://license.kerberos.io/verify"
        - name: LICENSE_PUBLIC_API_TOKEN
          value: "214%Ë†#ddfsf@#3rfdsgl_)23sffeqasSwefDSFNBM"
        - name : KERBEROS_CLOUD_QUEUE
          value: "https://queue.cloud.kerberos.io"
        - name : MQTTURI
          value: "tcp://mqtt.kerberos.io:1883"
        - name : MQTT_USERNAME
          value: ""
        - name : MQTT_PASSWORD
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: kerberos-vault
  labels:
    app: kerberos-vault
spec:
  ports:
  - port: 80
    targetPort: 80
    name: frontend
    protocol: TCP
  - port: 8081
    name: backend
    targetPort: 8081
    protocol: TCP
  selector:
    app: kerberos-vault
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kerberos-vault
  annotations:
    kubernetes.io/ingress.class: traefik
    #kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/proxy-body-size: 200m
spec:
  rules:
    - host: vault.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kerberos-vault
                port:
                  number: 80
    - host: api.vault.yourdomain.com #myvaultapi-storagedomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kerberos-vault
                port:
                  number: 8081
